import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import { Providers } from '../providers/providers'
import Menu from '@/components/Menu'
import { Container } from '@/components/Container'
import Footer from '@/components/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['300', '400', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon/favicon.ico'
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Menu />

          {children}

          <Container>
            <Footer />
          </Container>
        </Providers>
      </body>
    </html>
  )
}
